	.TITLE test1
	.ASECT
	.ENABL AMA
;	.=500
	.=173000	
	
start:
	nop
	mov	#1000,sp
	mov	#msg,r0
loop:
	movb	(r0)+,r1
	beq	done
	jsr	pc,tpchr
	br	loop

read:
	jsr	pc,kpchr
	cmp	r1,#3
	beq	done
	jsr	pc,tpchr
	jmp	read
done:
	halt

kps = 177560
kpb = 177562
tps = 177564
tpb = 177566

tpchr:
	tstb	tps
	bpl	tpchr
	movb	r1,tpb
	rts	pc

kpchr:
	tstb	kps
	bpl	kpchr
	movb	kpb,r1
	rts	pc

msg:
	.byte	15,12
	.ascii "Hello world!"
	.byte	15,12
	.byte	0


